### ISSUE TITLE
Possible bug in image projection

### ISSUE THREAD

**Issue by marip8** [Jmeyer1292/robot_cal_tools#40]
I came across a possible bug while developing a simulated observation generator in which the 2D calibration algorithms do not check whether the z value of the target point, projected into the camera frame, is greater than zero (i.e. actually in front of the camera). See [this file](https://github.com/Jmeyer1292/robot_cal_tools/blob/64602e30a9a6739a495d9fa85dd16253f2972893/rct_optimizations/src/rct_optimizations/extrinsic_camera_on_wrist.cpp#L54) for reference.

The issue here is:
- User provides a bad initial guess for the target or camera position (probably on accident)
- Some target observations show up behind the camera due to the bad guess
- The image projection math is no longer meaningful
- The optimization does not converge

I suggest we check that the z-value of the 3D target point in camera coordinates is greater than zero and throw an exception indicating that the initial transform guess was probably incorrect. I think this would be more helpful than the calibration silently failing to converge

@schornakj @drchrislewis is this a reasonable interpretation of this issue?

**Comment by marip8** [comment]
Here are a couple images of the simulated observations I made that brought this problem to light. The points with small normals represent camera locations and camera Z-axes. The single point with the larger normal is the target guess and target guess Z-axis.

## Good
The target is always in front of the camera positions
![good](https://user-images.githubusercontent.com/18411310/82103878-5d441000-96da-11ea-89bb-f840de1a38c3.png)

## Bad
The target is behind many camera positions and thus not technically visible
![bad](https://user-images.githubusercontent.com/18411310/82103883-603f0080-96da-11ea-842b-c601ed7d5e5c.png)

**Comment by schornakj** [comment]
I think that the pinhole camera model actually does still work when reprojecting object points that are behind the image plane, although this situation of course isn't feasible with real optics.

Seems like the core issue here is that if an object point is initially on the wrong side of the camera plane due to inaccurate initial values for transforms, the optimization tries to converge onto an incorrect local minimum. I suspect that strange discontinuous things happen to the residual as the reprojected point "flips" from -Z to +Z, which probably is a factor in preventing the optimization from converging.

We could check the sanity of initial guesses during a problem setup validation step. I'd avoid doing this check inside the cost function.

**Comment by drchrislewis** [comment]
@schornakj @marip8 This is a well understood problem. The ROS calibration does not use initial guesses from the user. Instead, there are well known methods for computing a reasonable PnP solution analytically from just a few observations. Then they let the optimization refine it. I never found this necessary because I always per-arrange the poses to the neighborhood of the solution. Even when I do robot driven intrinsic calibration, I use the forward kinematics and approximate target pose (grabbed from TF) to initialize the optimization. Having to add a layer of PNP code complicates things for a generic observation class where the cost being employed may change. 
If you want to do the PNP, look for papers under "calibration" Ax=B. An old office mate of mine at Purdue did his PhD on that. I didn't know what it was at the time, but now I do.

**Comment by marip8** [comment]
Distilling these comments:
- Sanity check the initial positions of the target and camera during problem set up
  - Raise an error if the observations can't all be seen correctly
- Don't throw an error in the optimization itself
- Using a PnP optimization to determine an initial guess
  - Possibly create a function/library to do this
  - Include in higher level code (i.e. creation of the calibration data/problem)

**Comment by marip8** [comment]
Addressed by #38 [here](https://github.com/Jmeyer1292/robot_cal_tools/blob/fb8029379db9a708670dc6ddfe4baec6bf26e5b9/rct_optimizations/src/rct_optimizations/extrinsic_hand_eye.cpp#L188); closing
